version: 1.0.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- cmd: nuget restore ./LiveScoreUpdateSystem/LiveScoreUpdateSystem.sln
build:
  project: ./LiveScoreUpdateSystem/LiveScoreUpdateSystem.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal